language: java
jdk:
- oraclejdk8
script: "./travis.sh"
install: true
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar"
before_deploy:
- export VERSION=$(cat pom.xml | grep -A 1 "sonar-auth-googleoauth-plugin" | grep
  version | sed 's@^[^>]*>\([^<]*\)<.*@\1@g')
- export RELEASE_JAR=$(ls target/sonar-auth-googleoauth-plugin-*.jar)
- echo "Deploying ${RELEASE_JAR} to GitHub"
deploy:
  provider: releases
  api_key:
    secure: rSHtAf8daq9kqpZaHGAfe+ArIOO1/TArti2XKcuHCSfS5zpareosAGKSWPgOukT/zamoKrHmHL58HL93SVyrkahFie86o9l4rMBQ9r1AX5xNilbqEJ5+7q5SknWzckzZx47JlI7Rd8I4yfAGsPtQPb7UflhQFGRgUKrCHpWA61r3z8J5P6ttdLPipQcbdsrDm4Nlv5zM1B4QXFsuDITpvwkYwpOF+BWyZSvU/AhFr3RfZGdlt5ZY+6ClbfiwSQi9lFNspBRbe6zeM6QWTh0UC49NwmONLXVb+soDD3ikeqomJnodpupCpSbcjyXhLt59Dg1JZ4Ty9nF6ks3mzL5/fKq2Tpf9k2DID/1V286qJ87kpWqx6y3/7BhbtjlirI8ADFnG4aLNfYJIJBAhHXXW2fWdHP4yS5BeO9NY5i1Q4UaLv1/lh1YE3ZhR/i/mSyMe44nPPA5YvZDSdhu7S7wQMTjHtsPYtXzers1LKC1WooA9m7135oKZtS94NJ3hxif2XWgDEmlR7+NNae5od4W5rCC93E0V7BWG9LruP3LL73hSM9VrVFnQoghil33sD3E/NM0VXxZqqP5LpCR7bYj9tX3TDmJK/YewsI5+hae06GdOkj2Rke4y6EmRFrTfFFVC/fIvn3NrDf837/mVapdNNPHtUTEpUFMPj5DUbN2RYrg=
  file: "target/RELEASE_NOTES"
  file: "${RELEASE_JAR}"
