language: java

jdk:
  - oraclejdk7

script: ./travis.sh

install: true

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    # for analysis
    - $HOME/.sonar
before_deploy:
  - export VERSION=$(cat pom.xml | grep -A 1 "sonar-auth-google-plugin" | grep version | sed 's@^[^>]*>\([^<]*\)<.*@\1@g')
  - git push --tags
  - export RELEASE_JAR=$(ls target/sonar-auth-google-plugin-${VERSION}.jar)
  - echo "Deploying ${RELEASE_JAR} to GitHub"
deploy:
  provider: releases
  api_key: "9c3a2beeb5c59cb519ccfc7ca55e0b1c70731258"
  file: "${RELEASE_JAR}"
  file: "target/RELEASE_NOTES"
  skip_cleanup: true
  on:
    tags: true